
import { Iuser } from './interface/IUser.jsx'
import { Relative } from './interface/IUser.jsx'

export const data: Iuser[] = [
	{
		firstName: 'Иван',
		lastName: 'Иванов',
		phone: '88005553535',
		email: 'van@mail.ru',
		organization: 'Aviasales',
		relative: Relative.colleague,
	},
	{
		firstName: 'Петя',
		lastName: 'Петров',
		phone: '89265784365',
		email: 'petya@mail.ru',
		organization: 'Ural',
		relative: Relative.colleague,
	},
	{
		firstName: 'Максим',
		lastName: 'Сидоров',
		phone: '89771234567',
		email: 'sid@gmail.com',
		organization: 'Storm',
		relative: Relative.friend,
	},
	{
		firstName: 'Лена',
		lastName: 'Иванова',
		phone: '88005563535',
		email: 'elen@mail.ru',
		organization: 'Sky',
		relative: Relative.classmate,
	},
	{
		firstName: 'Егор',
		lastName: 'Петров',
		phone: '89265784365',
		email: 'georg@mail.ru',
		organization: 'Forest',
		relative: Relative.relative,
	},
	{
		firstName: 'Никита',
		lastName: 'Сидоров',
		phone: '89771333567',
		email: 'ankv@gmail.com',
		organization: 'Rodster',
		relative: Relative.colleague,
	},
	{
		firstName: 'Маша',
		lastName: 'Иванова',
		phone: '88001111135',
		email: 'mary@mail.ru',
		organization: 'HighLevel',
		relative: Relative.classmate,
	},
	{
		firstName: 'Петя',
		lastName: 'Жилейкин',
		phone: '89265674365',
		email: 'jil@mail.ru',
		organization: 'Kamaz',
		relative: Relative.friend,
	},
	{
		firstName: 'Максим',
		lastName: 'Волков',
		phone: '89771234567',
		email: 'volk@gmail.com',
		organization: 'MosMetro',
		relative: Relative.classmate,
	},
	{
		firstName: 'Евгений',
		lastName: 'Иванов',
		phone: '88009873535',
		email: 'van@mail.ru',
		organization: 'Aviasales',
		relative: Relative.friend,
	},
	{
		firstName: 'Петя',
		lastName: 'Ким',
		phone: '89265784365',
		email: 'petya@mail.ru',
		organization: 'Sibir',
		relative: Relative.relative,
	},
	{
		firstName: 'Максим',
		lastName: 'Уваров',
		phone: '89771234567',
		email: 'sid@gmail.com',
		organization: 'Media',
		relative: Relative.classmate,
	},
	{
		firstName: 'Иван',
		lastName: 'Турынов',
		phone: '88005553535',
		email: 'van@mail.ru',
		organization: 'Sel',
		relative: Relative.friend,
	},
	{
		firstName: 'Петя',
		lastName: 'Стечкин',
		phone: '89265784365',
		email: 'petya@mail.ru',
		organization: 'Ural',
		relative: Relative.colleague,
	},
	{
		firstName: 'Максим',
		lastName: 'Рубанов',
		phone: '89771234567',
		email: 'sid@gmail.com',
		organization: 'Storm',
		relative: Relative.friend,
	},
	{
		firstName: 'Петя',
		lastName: 'Федотов',
		phone: '89265784365',
		email: 'petya@mail.ru',
		organization: 'Ural',
		relative: Relative.colleague,
	},
	{
		firstName: 'Максим',
		lastName: 'Федотов',
		phone: '89771234567',
		email: 'sid@gmail.com',
		organization: 'Storm',
		relative: Relative.friend,
	},
	{
		firstName: 'Иван',
		lastName: 'Чайка',
		phone: '88005553535',
		email: 'van@mail.ru',
		organization: 'Aviasales',
		relative: Relative.colleague,
	},
	{
		firstName: 'Александр',
		lastName: 'Петров',
		phone: '89265784365',
		email: 'petya@mail.ru',
		organization: 'Ural',
		relative: Relative.colleague,
	},
	{
		firstName: 'Александр',
		lastName: 'Сидоров',
		phone: '89771234567',
		email: 'sid@gmail.com',
		organization: 'Storm',
		relative: Relative.friend,
	},
];